/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter (Demoversion) for emWin version 5.14         *
*        Compiled Jan 12 2012, 10:15:30                              *
*        (C) 1998 - 2011 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: chinese_charcter.c                                    *
* Font:        ¿¬Ìå                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 16                                            *
* Range disabled: 0000 - FFFF                                        *
* Range enabled:  0000 - 007F                                        *
* Character disabled:  0x41 (65)                                     *
* Character enabled:   0x41 (65)                                     *
* Character enabled:   0x5357 (21335)                                *
* Character enabled:   0x5327 (21287)                                *
* Character enabled:   0x5307 (21255)                                *
* Character enabled:   0x52D7 (21207)                                *
* Character enabled:   0x5308 (21256)                                *
*                                                                    *
**********************************************************************
*/
#ifndef chines_test
	#define chines_test

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font. A good place would be GUIConf.H
*/

extern GUI_CONST_STORAGE GUI_FONT GUI_Fontchinese_charcter;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0020[ 16] = { /* code 0020, SPACE */
  XX_XX_X_,
  X__XXX_X,
  ___X_X_X,
  XXX____X,
  ___X_XXX,
  _X____XX,
  XX______,
  ________,
  _XXX____,
  XX__XX__,
  X__XX_XX,
  _XXXX__X,
  __XX___X,
  XX_XX_X_,
  XXXXXXXX,
  XX_X___X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0021[ 16] = { /* code 0021, EXCLAMATION MARK */
  __X_XX_X,
  XXX_____,
  X_X_XXX_,
  __XXXX_X,
  _XXXXX__,
  XX___XXX,
  _XX___XX,
  _XXXXX_X,
  X_XXX___,
  __XX__X_,
  XXX___X_,
  X__X_XXX,
  _X_X___X,
  XX_XX___,
  _XX_____,
  ____X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0022[ 16] = { /* code 0022, QUOTATION MARK */
  _XX___X_,
  ___XXX__,
  _X_XXXXX,
  _X_XX_X_,
  X__X___X,
  __XXXXXX,
  X___XX__,
  X__X_X__,
  XXX__XX_,
  _XX___X_,
  __X_XXX_,
  _X_XX__X,
  __X_XX__,
  _X_X__X_,
  _XX_XX__,
  X_XXX_X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0023[ 16] = { /* code 0023, NUMBER SIGN */
  _X___XXX,
  __XX___X,
  XXX__X_X,
  XXX__XX_,
  X__XXXX_,
  X_XXXXX_,
  ___XXXXX,
  X_XXX_X_,
  XX__XXX_,
  _X__XX__,
  ___X_XXX,
  XXXX_XXX,
  _X__X_X_,
  _X_X_XX_,
  XXXX_XX_,
  X_XX__XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0024[ 16] = { /* code 0024, DOLLAR SIGN */
  _X__X_XX,
  XXX_XXXX,
  X__XX_XX,
  _____X_X,
  _XXXX_XX,
  XX__XX__,
  _XX____X,
  _X_X__XX,
  X_X_X__X,
  _X__XX__,
  ___X___X,
  XXXXXX_X,
  __XXXX__,
  _X_X_X__,
  XX_X_XX_,
  X__XX_X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0025[ 16] = { /* code 0025, PERCENT SIGN */
  XXXXXXXX,
  XXX____X,
  X_XX_X_X,
  X__XXX_X,
  _XXXX___,
  XX__X_XX,
  _XXX__XX,
  XX___XX_,
  ____X__X,
  _X____XX,
  __X___X_,
  _X_XX_XX,
  _X_XXXX_,
  _X_X_X__,
  X__X_X_X,
  XX_X_XXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0026[ 16] = { /* code 0026, AMPERSAND */
  X_X_X_XX,
  _XXXXXXX,
  X__X___X,
  XX_XXXX_,
  X__XX_XX,
  X_XX___X,
  __XXXX_X,
  _____XXX,
  __XXXXX_,
  ___X__X_,
  XXX__X__,
  _XXXX__X,
  ______XX,
  XX_XXXXX,
  XX_X___X,
  X_X____X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0027[ 16] = { /* code 0027, APOSTROPHE */
  X__XXXX_,
  XX______,
  X_XXXXXX,
  XX____X_,
  X_XXX__X,
  __XX_X__,
  X_XXX_X_,
  _____X_X,
  ___X_XXX,
  __X_XX_X,
  X__XX__X,
  _X_XXXXX,
  _______X,
  X___X_X_,
  _____XX_,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0028[ 16] = { /* code 0028, LEFT PARENTHESIS */
  X__X__XX,
  ___XXXX_,
  XXXXX_XX,
  X___XX_X,
  _X__XX_X,
  XX______,
  _X_X_X_X,
  XX__XX__,
  _X__X___,
  __XXXXXX,
  _X_XXX_X,
  ___X___X,
  ___XX_X_,
  _XXXXX_X,
  _XX___XX,
  X_X_X__X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0029[ 16] = { /* code 0029, RIGHT PARENTHESIS */
  __X__XX_,
  ___X__XX,
  _XXXX_XX,
  _X_X___X,
  _X_XXXXX,
  _X___X__,
  XX___X__,
  X__X___X,
  XX_X__X_,
  X_XX_X_X,
  _XX_XX__,
  XXXXXXXX,
  __XXX___,
  ____X_X_,
  X__X____,
  XXX__X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_002A[ 16] = { /* code 002A, ASTERISK */
  _X_XX_X_,
  X___XXXX,
  X_X_X_X_,
  __XX__X_,
  X_X_XXXX,
  __X_XXX_,
  XXXXX___,
  _XXXX___,
  X____X_X,
  _XXX_X_X,
  X_XXX_XX,
  X_XX_X_X,
  _____X_X,
  _XXX___X,
  XXXX__X_,
  XX_X__X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_002B[ 16] = { /* code 002B, PLUS SIGN */
  __X__XX_,
  X_X___X_,
  __XX___X,
  ____X_X_,
  X_XX_XXX,
  __X_X__X,
  XX______,
  _X__XXX_,
  XX___X_X,
  XX_XX_X_,
  XX______,
  _X_XX_XX,
  __X__X_X,
  _______X,
  __XX___X,
  XX__XXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_002C[ 16] = { /* code 002C, COMMA */
  _XX_X___,
  _XXXXX__,
  X_X_____,
  _XX_X__X,
  _X__X_XX,
  _X_XX_XX,
  X_XXXX__,
  X_XXXXXX,
  X__X__XX,
  _X__X_XX,
  ____XXX_,
  X_XX___X,
  __XXXX__,
  XXX___XX,
  X__X___X,
  XXXX_XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_002D[ 16] = { /* code 002D, HYPHEN-MINUS */
  XX_XXXXX,
  _XX___X_,
  __XXX_XX,
  XXXX_X_X,
  _X_X___X,
  XX_XX___,
  __X_XX_X,
  X___X_X_,
  ____X_XX,
  XXXX_X__,
  X_XX_XXX,
  ___X_XXX,
  __XXXXX_,
  X____XXX,
  __X_X_X_,
  X_XXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_002E[ 16] = { /* code 002E, FULL STOP */
  XX_____X,
  XXXXX___,
  _XX__X__,
  __XX__X_,
  X___X__X,
  __X___X_,
  XX___X__,
  _XX_X_XX,
  _X_XXX__,
  X____X_X,
  __XX___X,
  ___X___X,
  __X____X,
  _XX_XX__,
  _____XXX,
  _X_XXX_X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_002F[ 16] = { /* code 002F, SOLIDUS */
  XXXX_XXX,
  XX_X__XX,
  _XX_X_XX,
  X_X_XXX_,
  X__X__XX,
  X_X_XXXX,
  _XX__X_X,
  _XXXXX_X,
  _XXXXX__,
  X_X_X_X_,
  ______X_,
  X_X__XXX,
  ______XX,
  ____XX_X,
  X__XX___,
  X__X_X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0030[ 16] = { /* code 0030, DIGIT ZERO */
  X_XXXX_X,
  __X_X__X,
  __X_XXX_,
  XX__XX_X,
  _XX__XX_,
  XX_X_XXX,
  X___X__X,
  XXXX_X__,
  _X__X_XX,
  X_X_X___,
  XX______,
  _XXX_X_X,
  __XXXXX_,
  _XX__XX_,
  X__X_X__,
  _XX__X_X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0031[ 16] = { /* code 0031, DIGIT ONE */
  ___X_XX_,
  ________,
  XXX_____,
  XXX_XX_X,
  XXXX__XX,
  XX_X_XXX,
  ___XX__X,
  XXXXX__X,
  XXX___X_,
  X____XX_,
  X_XXX__X,
  X_____XX,
  ___X__X_,
  ___XX__X,
  ____XXXX,
  X_X_X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0032[ 16] = { /* code 0032, DIGIT TWO */
  ___XXX_X,
  X__XX___,
  __X__X__,
  XX__XXX_,
  _____XX_,
  X_X_XX_X,
  _XX__XXX,
  __XX____,
  ____XX_X,
  XXXX_XX_,
  _X_XXX_X,
  XX_XX___,
  _X__XXXX,
  XXX__XX_,
  __XX_XXX,
  __X_XXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0033[ 16] = { /* code 0033, DIGIT THREE */
  X_X_XX__,
  __X____X,
  X_X__X__,
  _X_X__X_,
  ___X_X_X,
  __X___X_,
  _XXX_X__,
  __X___X_,
  X_X__X_X,
  XX__X__X,
  _XX_XX__,
  _____XXX,
  ____XX_X,
  X__X__X_,
  _XX_XX_X,
  X_X_X_XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0034[ 16] = { /* code 0034, DIGIT FOUR */
  _XX__X__,
  XX_XX_X_,
  _XXX_X__,
  ___X_X_X,
  X_______,
  XX_XX___,
  __XXX_XX,
  XX____XX,
  XXXX__X_,
  XX_XX___,
  XXXXX_X_,
  _X_XX___,
  _X_X__X_,
  _XX_X___,
  __X____X,
  ___XXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0035[ 16] = { /* code 0035, DIGIT FIVE */
  X_X__X__,
  XXXXX__X,
  XXX_XXX_,
  ____X__X,
  X__X_XXX,
  _X_XXXXX,
  X_XXXX__,
  XXXX_XX_,
  __XX__X_,
  _XXX_XXX,
  XX_____X,
  _XX__XXX,
  __X__X__,
  ___X_X__,
  XXXXXXX_,
  XX____XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0036[ 16] = { /* code 0036, DIGIT SIX */
  XXX_XX__,
  _XX_X_XX,
  X_XXXXX_,
  _XX_X_X_,
  _XX_____,
  __XX___X,
  _X_X__X_,
  ____XXXX,
  XXXX_X__,
  X_XX_XX_,
  ____XXXX,
  _XXXXX__,
  _X_XX___,
  _XX_X_XX,
  X__X__X_,
  __XX_X_X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0037[ 16] = { /* code 0037, DIGIT SEVEN */
  _X_X_X_X,
  _XX_X___,
  XX___X__,
  XX_X__X_,
  _XXXX_XX,
  __XXXX__,
  XX_____X,
  __XX___X,
  _XXXXX__,
  __XXX__X,
  XXXX_XX_,
  XX__X_XX,
  __XXX_X_,
  ___XXXX_,
  _X__X__X,
  XXXXX__X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0038[ 16] = { /* code 0038, DIGIT EIGHT */
  XX_XXX__,
  X_XXX_X_,
  X_XXX__X,
  __XX___X,
  X____XX_,
  _X___X__,
  XXXXXXX_,
  X__XX___,
  __X____X,
  X_X_X_XX,
  __XX__X_,
  XX_XX_X_,
  _XX__X_X,
  XXXX_X_X,
  ____X__X,
  _X__X__X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0039[ 16] = { /* code 0039, DIGIT NINE */
  _XXXXX_X,
  X___XXXX,
  X__X_X__,
  X_X_XX_X,
  X__XX___,
  XX_____X,
  XX__XXXX,
  X____X__,
  X___X__X,
  ___X_X_X,
  ____X_X_,
  _X__XXXX,
  X_X___XX,
  X_XXXXX_,
  XX__X_XX,
  _X_X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_003A[ 16] = { /* code 003A, COLON */
  __XX_X_X,
  ___XX_XX,
  XXXX___X,
  XXX___X_,
  _X___X__,
  __XXX_X_,
  X_X___XX,
  _X_XXX__,
  __XXXXX_,
  _X___X_X,
  X_______,
  X__X__X_,
  _XXXXXX_,
  _XXX_X_X,
  _XX_XXXX,
  _XX_X_X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_003B[ 16] = { /* code 003B, SEMICOLON */
  X____X__,
  ___XXXX_,
  _X_XXXX_,
  __XXXXX_,
  _X__XX__,
  X_XX___X,
  __X___XX,
  XX__X_X_,
  X___XXXX,
  _X__X_X_,
  X_XXX__X,
  _XX_XXXX,
  XX_XXXX_,
  __XX___X,
  XX_XX_X_,
  _XX___X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_003C[ 16] = { /* code 003C, LESS-THAN SIGN */
  ___XXXXX,
  XX__X__X,
  XXXXX_XX,
  XX_XXX_X,
  X_X__X__,
  XX__X_XX,
  XX__X_XX,
  ____X_XX,
  XXXXX___,
  _X__X_XX,
  _XXXXX_X,
  __X__XX_,
  _XX___XX,
  _XXXX_XX,
  XXXXXXX_,
  _X____X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_003D[ 16] = { /* code 003D, EQUALS SIGN */
  X_X__X__,
  XXX_XXX_,
  _X_XX___,
  _XX__X_X,
  X_X_XXX_,
  XXX_XX__,
  _XXXX_X_,
  ___XXXXX,
  XX_X____,
  _XX_XX__,
  ____XX__,
  X___X_XX,
  XX_____X,
  __X___XX,
  _XX_X__X,
  __X_XXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_003E[ 16] = { /* code 003E, GREATER-THAN SIGN */
  XXX_XXX_,
  ___XX___,
  X_X_X_XX,
  _____XX_,
  _X__X_X_,
  X__X_XX_,
  X____XXX,
  XX_X_XXX,
  X___XXXX,
  __XXXX__,
  XX_XX_X_,
  X_____X_,
  _X_XX_X_,
  XXXXX__X,
  _X__XX__,
  _X_XX__X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_003F[ 16] = { /* code 003F, QUESTION MARK */
  ___XXX__,
  _XX_XXXX,
  ___X___X,
  ___XX_X_,
  _X__X___,
  ___XX_XX,
  ___X_XX_,
  X__XXX_X,
  _X_X_XXX,
  _X____X_,
  XXX____X,
  X_X__XXX,
  XX_X____,
  X_X_XX_X,
  XXX_XXXX,
  ___X_X_X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0040[ 16] = { /* code 0040, COMMERCIAL AT */
  _XX__XX_,
  __XXX__X,
  _XX__X_X,
  _X_XXX_X,
  X_X_X___,
  XXX__XXX,
  _XX___X_,
  _XXX_X__,
  ________,
  __XX____,
  XXX_XXXX,
  X_____X_,
  _X__XX_X,
  _XXX__X_,
  XX__XXXX,
  __XX___X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0041[ 16] = { /* code 0041, LATIN CAPITAL LETTER A */
  _X_X_X_X,
  ___XXX__,
  _X_XX_XX,
  XX_____X,
  X___X___,
  _XXX__X_,
  _XXX__X_,
  _X______,
  _______X,
  X__XXXX_,
  XX_X_XX_,
  __X__XXX,
  XXX_XX_X,
  X_X__X_X,
  X__XXX__,
  __XX_X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0042[ 16] = { /* code 0042, LATIN CAPITAL LETTER B */
  _X_X_XX_,
  XXX_X___,
  _XX__XXX,
  ______X_,
  _XX_XX_X,
  _______X,
  __XXXX__,
  X_X_____,
  _X_X_XX_,
  _X_XX_X_,
  ___X__X_,
  _XX__XX_,
  _X_X_X__,
  _XX__XX_,
  XX_XX___,
  ______X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0043[ 16] = { /* code 0043, LATIN CAPITAL LETTER C */
  XXX__XXX,
  X___XX_X,
  _X__X_XX,
  XX_X__X_,
  _XX_XXX_,
  _____XX_,
  X_XXX_XX,
  X__X_XX_,
  XX_XXXX_,
  X_XX_X_X,
  _XX_X_XX,
  X_____XX,
  XXXX_XX_,
  __X___X_,
  _____XXX,
  _X_XXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0044[ 16] = { /* code 0044, LATIN CAPITAL LETTER D */
  X_XXXXXX,
  _X_XX_X_,
  __X_XXXX,
  X_XX___X,
  X___XXXX,
  _XXXXX__,
  _X_X_X__,
  _XX_XXXX,
  XX_X___X,
  _X___X__,
  X_X____X,
  _X__X_X_,
  __X_X__X,
  XXX_XX__,
  _XX_X_X_,
  X_X_XXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0045[ 16] = { /* code 0045, LATIN CAPITAL LETTER E */
  XX__XXXX,
  _XXXXX_X,
  X____X_X,
  ____XX_X,
  X____X__,
  XXXXXXXX,
  XX___XXX,
  _XXX__XX,
  XXXXX__X,
  XXXXX_XX,
  X__XX_X_,
  X_X__XXX,
  XXX_X_XX,
  X_X_X___,
  X_XX___X,
  _XX__XXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0046[ 16] = { /* code 0046, LATIN CAPITAL LETTER F */
  X____XXX,
  X__XXXXX,
  _X___X__,
  XXX_X_X_,
  _XX_X_XX,
  ____XX_X,
  XX_XX__X,
  XXXXX_XX,
  X___XXXX,
  __X_X_XX,
  _X_XXX__,
  XX__X_X_,
  __XX__X_,
  _XX_X_X_,
  XXX_X__X,
  X__X_X_X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0047[ 16] = { /* code 0047, LATIN CAPITAL LETTER G */
  __X___X_,
  XXXXXX__,
  XX___XXX,
  _XXX_XXX,
  _____X__,
  X___X___,
  XX__X_XX,
  XXX__X_X,
  __X_XXXX,
  XX___X_X,
  __X_XX_X,
  _XX__XXX,
  XX_X__XX,
  X_X_X_X_,
  __XX__X_,
  _XX_XX_X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0048[ 16] = { /* code 0048, LATIN CAPITAL LETTER H */
  _XX__XX_,
  __X_XXX_,
  _X_X_XX_,
  __XX_X__,
  XXX_X__X,
  XXXX____,
  X_X__X_X,
  __XXXX__,
  _X__X_X_,
  X____X_X,
  XXXXX___,
  _XX_XXX_,
  __X_XXX_,
  _XX___XX,
  X__XXXX_,
  XX_XXX_X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0049[ 16] = { /* code 0049, LATIN CAPITAL LETTER I */
  ___X__X_,
  __X_XXXX,
  XX__XXXX,
  __X_XX__,
  XXX___X_,
  XXXX___X,
  __X___X_,
  __X_X___,
  _XX___X_,
  X___X__X,
  _X_____X,
  _X_XX_XX,
  XX__XX__,
  __XX_XX_,
  __X_____,
  _X_XX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_004A[ 16] = { /* code 004A, LATIN CAPITAL LETTER J */
  _X_XXX__,
  XXXXXXXX,
  X__XX_X_,
  _X__XXXX,
  ____XXXX,
  X_____XX,
  XX__XX_X,
  XX__X___,
  _XXXXX_X,
  XX__X__X,
  XX__XXXX,
  ____X_X_,
  __XX___X,
  XX_____X,
  ____XX__,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_004B[ 16] = { /* code 004B, LATIN CAPITAL LETTER K */
  XX_XX_XX,
  X__XXXXX,
  X____X_X,
  XXXX__XX,
  _______X,
  _____X_X,
  _XXXXX__,
  XXXXX_X_,
  XXXX____,
  X_X__XX_,
  XXXX_XX_,
  XXXXXXXX,
  XX_X_X_X,
  X_XX_X_X,
  X__X_X_X,
  __XX__X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_004C[ 16] = { /* code 004C, LATIN CAPITAL LETTER L */
  XX_X_X__,
  XX_XXX_X,
  XX_XX___,
  XX__XX__,
  XXX__XXX,
  XXX_XXXX,
  X_______,
  ___X__XX,
  __XX_XXX,
  XXXX_XXX,
  __XX__X_,
  X_X___X_,
  ________,
  _X__XXXX,
  X_XX_X_X,
  XX___XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_004D[ 16] = { /* code 004D, LATIN CAPITAL LETTER M */
  _XX___XX,
  XX_XXXX_,
  ___X_XXX,
  XX_X____,
  XX___X_X,
  __X_X___,
  ___X___X,
  __XXXXXX,
  X_XX_XXX,
  _XX_X___,
  _X__XXXX,
  _XXXXXXX,
  X_____X_,
  X_XXX_XX,
  ___X_XX_,
  ____X_XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_004E[ 16] = { /* code 004E, LATIN CAPITAL LETTER N */
  X_XX_X_X,
  ____XX__,
  XX_X____,
  X__X__XX,
  __XX___X,
  _X_XXXX_,
  _XXXXX__,
  X__X_XXX,
  XXX_____,
  X_XXX___,
  X______X,
  X_X__XX_,
  ___XXX_X,
  _X_XXX_X,
  __XX_XX_,
  X_X_XX_X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_004F[ 16] = { /* code 004F, LATIN CAPITAL LETTER O */
  _X____XX,
  _XX_XXXX,
  _X_XX_X_,
  ____X_XX,
  __X__XXX,
  _X_XX_XX,
  _XXXXX_X,
  X______X,
  ____X___,
  _X_X_XX_,
  X_XXX_X_,
  ___XX_XX,
  X_XXX_XX,
  __XXX__X,
  _XX__X__,
  X_X____X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0050[ 16] = { /* code 0050, LATIN CAPITAL LETTER P */
  ____XX_X,
  X__XXX_X,
  X__XX_X_,
  XXX_X___,
  XX_X__XX,
  __X___XX,
  __XX_X_X,
  _X______,
  XXXX_XX_,
  X__X_XX_,
  ___XXX__,
  ______X_,
  _____XX_,
  XX_X____,
  __X_____,
  X__XX__X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0051[ 16] = { /* code 0051, LATIN CAPITAL LETTER Q */
  X_XXX_X_,
  X_XXX___,
  ___XX___,
  _X_X_X__,
  XX__X_XX,
  X_X__XX_,
  X_X__X_X,
  _X_X_X__,
  _X__XXX_,
  __XXX_X_,
  __X_XX_X,
  X_XX_XXX,
  X_X__XX_,
  X_XX___X,
  XXXX_XXX,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0052[ 16] = { /* code 0052, LATIN CAPITAL LETTER R */
  _XX__X__,
  _XXXXX__,
  _X__X___,
  __XX__XX,
  __XX_XXX,
  _X_X_X__,
  _X_XX_XX,
  _____X__,
  __XXX__X,
  XX__X_X_,
  XXXXX__X,
  X_X___X_,
  __XXX_XX,
  _X_XX_X_,
  X__X__XX,
  X__X__X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0053[ 16] = { /* code 0053, LATIN CAPITAL LETTER S */
  X__X____,
  ___XX___,
  ___X____,
  __X_XXXX,
  __X_X__X,
  XX_X_XX_,
  X___X___,
  ___X__X_,
  X__XX__X,
  __XX_X_X,
  ________,
  X_XX_XXX,
  X_XXX__X,
  X_X__XXX,
  _X_X____,
  XX_XX_X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0054[ 16] = { /* code 0054, LATIN CAPITAL LETTER T */
  XX_X_X__,
  XXX_XXX_,
  _X___X__,
  _XX_XX__,
  XXXX_X__,
  X_X_XX__,
  XX_XXXXX,
  XXXXX_XX,
  ____XXX_,
  _XX__X__,
  XX__XXX_,
  XXX__XX_,
  X_X___X_,
  _X_XXX__,
  ___X___X,
  X_X_X_X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0055[ 16] = { /* code 0055, LATIN CAPITAL LETTER U */
  _XX____X,
  XX__X__X,
  _XXXX_X_,
  X_XXXX__,
  XXX_XXXX,
  X_X___XX,
  XX__XX__,
  X____XXX,
  X__X_XXX,
  _X__X_XX,
  XXXX_X_X,
  ___X__XX,
  X_______,
  __X_XX__,
  XX____X_,
  XXXX_XXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0056[ 16] = { /* code 0056, LATIN CAPITAL LETTER V */
  XX_XXX__,
  ___XXXXX,
  _____XXX,
  XX_XXXXX,
  ___X_X__,
  XX_XX__X,
  X_X___X_,
  _XXXXXXX,
  XX__X___,
  _XX_X_XX,
  _XXX__X_,
  _X_XX_X_,
  X_XXXX_X,
  XX_X_XX_,
  _XX__XX_,
  XX_____X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0057[ 16] = { /* code 0057, LATIN CAPITAL LETTER W */
  _XX_X__X,
  __XXX___,
  X_X_X___,
  XXX___XX,
  ____XXXX,
  _X_XXX__,
  __X__X__,
  _X__XX_X,
  _X____X_,
  _X___X_X,
  _X__XXXX,
  _XXX_XXX,
  X__XXX_X,
  X_X_X_X_,
  XX_XX__X,
  XX___X_X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0058[ 16] = { /* code 0058, LATIN CAPITAL LETTER X */
  __X__X_X,
  X__XXXX_,
  _X__XXXX,
  X____X__,
  XXXXX_X_,
  X_XX____,
  XX__X_X_,
  X_X_XX__,
  X__X_X_X,
  ___X_X_X,
  X_____XX,
  _XXXX_X_,
  XX___X__,
  _X_X_XXX,
  XXXX_X_X,
  XXX____X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0059[ 16] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XX__X__X,
  __XXX_XX,
  X_X__X__,
  ___XX___,
  XXX_X__X,
  __XXXX_X,
  _XXXX__X,
  X_XXX___,
  _XXX_X_X,
  __X_X___,
  XXXXX_X_,
  XX_X_XXX,
  X___XXXX,
  X_X___X_,
  _XX_XXX_,
  X_X_XX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_005A[ 16] = { /* code 005A, LATIN CAPITAL LETTER Z */
  X____XXX,
  XXX__XXX,
  _X___X_X,
  XX_XX_XX,
  _XXXX___,
  _X___XXX,
  X____XX_,
  _XXX____,
  ___X__XX,
  __XXXX_X,
  __XXXX__,
  XXXXXXX_,
  XX_X__X_,
  ____X__X,
  _X_X_XXX,
  _X_XX_X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_005B[ 16] = { /* code 005B, LEFT SQUARE BRACKET */
  X_XX____,
  XXX_X_XX,
  XXX__XX_,
  _X____XX,
  _XX_X_XX,
  _X_____X,
  ___X_XXX,
  _XXXXXX_,
  __XXX_XX,
  X_XX__X_,
  ____XX_X,
  _X_XX_XX,
  X_XX__X_,
  _____X__,
  XXX_XX__,
  X__X_XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_005C[ 16] = { /* code 005C, REVERSE SOLIDUS */
  XXXXXXXX,
  _XXX_X_X,
  X__X_XXX,
  __X_____,
  X__XXX__,
  __XXXXXX,
  _XXXX_XX,
  X_XX_XXX,
  _X__XX__,
  _XXX__XX,
  ___XX__X,
  X__XX_X_,
  XX__X_XX,
  X___X_XX,
  XX___XX_,
  _X_X_XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_005D[ 16] = { /* code 005D, RIGHT SQUARE BRACKET */
  ___XX___,
  _X_XX_X_,
  X_X_XX_X,
  XX_XXX__,
  X___XXX_,
  X_XX____,
  _X_XX_XX,
  XXX_X_XX,
  XXX_XX__,
  XX_XXX__,
  __X_____,
  _XXXXXXX,
  X_XXX__X,
  X___XXXX,
  X__XXX_X,
  X__XXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_005E[ 16] = { /* code 005E, CIRCUMFLEX ACCENT */
  _X_X__X_,
  X__X____,
  X__XX_XX,
  __XX__XX,
  _XXXXXX_,
  _X__X_X_,
  __XX__XX,
  ______XX,
  XX__X_XX,
  _X__XX__,
  XXX_XXX_,
  __XX__X_,
  XXX__XX_,
  _____X_X,
  XX_X___X,
  __X__X_X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_005F[ 16] = { /* code 005F, LOW LINE */
  _XX_X__X,
  X__XX_XX,
  X_X__X_X,
  X___XXXX,
  _XX__X__,
  XXX_XXXX,
  X_X___X_,
  __XX_X_X,
  XXX___XX,
  XX_X__X_,
  X__X_X_X,
  XX_XXXXX,
  X_X__X__,
  X__XXX_X,
  ____XXXX,
  X_XXXX_X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0060[ 16] = { /* code 0060, GRAVE ACCENT */
  _XX___X_,
  _______X,
  XX_XX__X,
  XXX_XX__,
  X_XXX___,
  X__X_XXX,
  _X_XXXXX,
  XX___X__,
  X_XXXX_X,
  X_____X_,
  _X_X__XX,
  X_XX_XX_,
  XXXXX__X,
  _____X__,
  _XX_X_XX,
  ____XX_X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0061[ 16] = { /* code 0061, LATIN SMALL LETTER A */
  XXX____X,
  __X_X___,
  _XXX_XXX,
  XXXX_X__,
  X_X__X__,
  X__XXXX_,
  X___XXX_,
  XXXX____,
  __XX_X_X,
  X_X_XXXX,
  _XX_XXX_,
  X__XX_XX,
  XX_XXX_X,
  ___X___X,
  X_X_X___,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0062[ 16] = { /* code 0062, LATIN SMALL LETTER B */
  X_X_X_XX,
  XX_X___X,
  X__X__XX,
  X_XX_XXX,
  _X_XX___,
  XXX__X__,
  XX______,
  ___XX__X,
  _XX___X_,
  X_X_XXX_,
  XXX___X_,
  X__X__X_,
  XXX_____,
  X___XXX_,
  X_X_X___,
  __XX_XXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0063[ 16] = { /* code 0063, LATIN SMALL LETTER C */
  XX_XX_XX,
  XXXXX___,
  __XXX_XX,
  __X_X_XX,
  _X_X__X_,
  _XXX__XX,
  XX____XX,
  ______X_,
  __XX__X_,
  X______X,
  XX_XX_XX,
  __XX_XXX,
  XX____X_,
  X__X__XX,
  __XXX_XX,
  XXX_X_X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0064[ 16] = { /* code 0064, LATIN SMALL LETTER D */
  X_____XX,
  _XXX____,
  __XXX_X_,
  XX__XX__,
  X_XXXXXX,
  X_______,
  X_X_XX__,
  X__XX_XX,
  _XX__X_X,
  XXXX____,
  ___XXX_X,
  _XXX__X_,
  XX_XXX_X,
  ___XX___,
  X__XXXXX,
  ___XXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0065[ 16] = { /* code 0065, LATIN SMALL LETTER E */
  __XXX_X_,
  XX_XX__X,
  __XXX__X,
  _XXX____,
  X_XX____,
  _____X_X,
  __XXX_XX,
  X___XXXX,
  XX__XX__,
  XX__XXXX,
  X_X_XXXX,
  X____XXX,
  XX_XX_XX,
  X__XXX__,
  __X_X__X,
  _X_XX_XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0066[ 16] = { /* code 0066, LATIN SMALL LETTER F */
  __XX__XX,
  __X___XX,
  _XX_X___,
  _X_X__XX,
  _X_X_XXX,
  _XXXX__X,
  XX___X_X,
  _X__XXX_,
  X_XX__XX,
  XX_XXXXX,
  __X_X__X,
  _X_X_XX_,
  XX__XXX_,
  ___X__X_,
  ____XX_X,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0067[ 16] = { /* code 0067, LATIN SMALL LETTER G */
  ______X_,
  ____X___,
  _XXX__XX,
  XX_X__XX,
  _XXX_X__,
  XXXXXX__,
  _XXX_XXX,
  _X_XX__X,
  X___X__X,
  _XXX___X,
  ________,
  X_____XX,
  XXX_XXX_,
  ___X_XX_,
  X___XXX_,
  _X_X___X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0068[ 16] = { /* code 0068, LATIN SMALL LETTER H */
  _X_XX_X_,
  X__X__X_,
  __X__X__,
  ___X____,
  X__X___X,
  ____XX__,
  X___X__X,
  __XXX_X_,
  X_XXXXX_,
  X__X___X,
  XX__XXX_,
  XX_XX_X_,
  XX_X__XX,
  X__X_XX_,
  X_X_XXX_,
  _XX___XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0069[ 16] = { /* code 0069, LATIN SMALL LETTER I */
  XXX_X_X_,
  X__XX_XX,
  XXXXX_XX,
  X___XX__,
  X__X_XX_,
  X___X__X,
  ___X__X_,
  ___XXX__,
  ___XXXX_,
  __XXXX__,
  X_XX_X_X,
  _XX__XXX,
  XXXX_X_X,
  X__X_XX_,
  _X_XXX_X,
  __X_X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_006A[ 16] = { /* code 006A, LATIN SMALL LETTER J */
  XXX_____,
  _X____X_,
  __X__XX_,
  XXX_X_XX,
  XXXX__XX,
  XXXX__XX,
  _XXXXX_X,
  XXXX_X_X,
  XX__X___,
  X_X_XX_X,
  _XXX_XXX,
  _XXXX_X_,
  X_X_X_X_,
  ___XXX_X,
  __XXX___,
  _X__X_XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_006B[ 16] = { /* code 006B, LATIN SMALL LETTER K */
  _X__X_XX,
  _XXXXXXX,
  X_X_X___,
  XX_X_XXX,
  XXXXX___,
  XXXX____,
  _X_XXX__,
  XX__X_X_,
  _X______,
  ___X__X_,
  _X__XXX_,
  _X___XXX,
  XXX_X__X,
  X___X___,
  _XX__XXX,
  ______X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_006C[ 16] = { /* code 006C, LATIN SMALL LETTER L */
  X_X____X,
  XXX___XX,
  _XX_XX__,
  X_XX_X__,
  _X_X__XX,
  X_____XX,
  __XX_X__,
  _XX____X,
  ____XXXX,
  _X____X_,
  XX____X_,
  _X_XXXX_,
  X_XX_X__,
  __XXX_XX,
  ____X__X,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_006D[ 16] = { /* code 006D, LATIN SMALL LETTER M */
  _X_X__XX,
  XXX_XXX_,
  XXX__X__,
  __X_XX__,
  _XXXX__X,
  _____XX_,
  X_X__X__,
  _X_X_XXX,
  XX___XXX,
  _X__XX__,
  XXXXX_XX,
  XX__X_XX,
  XX_X_XX_,
  ____X_XX,
  XXXX_XX_,
  __X__XXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_006E[ 16] = { /* code 006E, LATIN SMALL LETTER N */
  ___XX__X,
  __XX____,
  X_X__X__,
  XXX_XXXX,
  X__X_X_X,
  XXXXXXX_,
  _X_XX___,
  X_X__XX_,
  ___X____,
  _X__XX__,
  X__XXX_X,
  X__XX_X_,
  X_X_XX_X,
  X_XX___X,
  X___X_X_,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_006F[ 16] = { /* code 006F, LATIN SMALL LETTER O */
  X_XXX_X_,
  ___XXXXX,
  XXX__XX_,
  __XX__XX,
  X__XXXXX,
  _XX_X_XX,
  X___X__X,
  X_XX_X_X,
  X_XX___X,
  _XX___X_,
  XXX_XXX_,
  _XX_XXXX,
  XX__XXXX,
  X____X_X,
  _X_X___X,
  ___XXX_X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0070[ 16] = { /* code 0070, LATIN SMALL LETTER P */
  __XXX__X,
  XX_____X,
  X_XX_XX_,
  _X_XXX__,
  _XXX_XXX,
  ___XXXXX,
  XX___X__,
  _XXXXXX_,
  XX_X_XX_,
  __XX__X_,
  __X_X___,
  X_XX_XX_,
  X__X__X_,
  __X____X,
  _X_XX___,
  X_X_X_XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0071[ 16] = { /* code 0071, LATIN SMALL LETTER Q */
  X___X___,
  X__XXX__,
  X_X_XX__,
  XXX_____,
  _XXXXXXX,
  ___XX_X_,
  XX___X_X,
  _XX_____,
  _XXXXXX_,
  _X__XXXX,
  _______X,
  ____XXXX,
  _X_X__X_,
  X____X_X,
  XX____XX,
  _X_X_X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0072[ 16] = { /* code 0072, LATIN SMALL LETTER R */
  XX______,
  XX_____X,
  XXXXX__X,
  ______XX,
  X__XX_XX,
  _XX_____,
  X_X_XX_X,
  X_X_X__X,
  XX_____X,
  __XXX_X_,
  X___XX_X,
  _____XX_,
  X___X_XX,
  __X_XXX_,
  _XX_XXXX,
  X_X___XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0073[ 16] = { /* code 0073, LATIN SMALL LETTER S */
  _XX_____,
  XXX_XX__,
  _X___X__,
  X__XX_XX,
  X_XXX__X,
  XXX__XXX,
  __XXXX_X,
  XXX_XXX_,
  _XX_X__X,
  X__X_X_X,
  X_XX_X__,
  X___X_XX,
  _______X,
  ____X_XX,
  XXXX____,
  _XX_XXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0074[ 16] = { /* code 0074, LATIN SMALL LETTER T */
  XXX_X___,
  ___X____,
  X_XXX__X,
  XX_XX___,
  _X_XX__X,
  ___X___X,
  XXX___XX,
  ____XX_X,
  ___XXXXX,
  _X_X_X_X,
  _XXX_XXX,
  X_____X_,
  X__XXXX_,
  X_X_XX__,
  XXXXXX__,
  XX___X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0075[ 16] = { /* code 0075, LATIN SMALL LETTER U */
  _X_XXX_X,
  _XXXXX_X,
  _X_X_XX_,
  XX___X__,
  _X_XX_XX,
  X__X_X_X,
  _XXX____,
  __XXX_XX,
  X_X_XXXX,
  X_XXX_XX,
  ____XX__,
  X_X__XXX,
  __XXXX__,
  X__XX___,
  _XXX_XX_,
  _X__XXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0076[ 16] = { /* code 0076, LATIN SMALL LETTER V */
  __X_X___,
  X_X__XXX,
  X_XX__XX,
  X_X___XX,
  X_X_XXX_,
  XXX_XX_X,
  X__XXXXX,
  XX_XX_X_,
  _XXXX_X_,
  _X__X_XX,
  XX____X_,
  XXX__XX_,
  X______X,
  X_X___X_,
  _X_X_XX_,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0077[ 16] = { /* code 0077, LATIN SMALL LETTER W */
  XX_XXX_X,
  X__XXX__,
  ___XX___,
  _X_XXXXX,
  X_XXX_XX,
  XXX_____,
  ___XXX__,
  XXXXXX_X,
  X_XX__X_,
  XXXX_X_X,
  XXXXX_XX,
  _____XXX,
  __X__X_X,
  X__X__X_,
  X_X__X_X,
  __XX_X_X};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0078[ 16] = { /* code 0078, LATIN SMALL LETTER X */
  X__X___X,
  _XX__XX_,
  _XXXX_XX,
  __XXXX__,
  _X__XXX_,
  X__XX___,
  _XXX__X_,
  ___X_XX_,
  XXX_XX_X,
  __X__X_X,
  XXXXXX_X,
  _X___XX_,
  X_XXX___,
  __X_X_X_,
  XX_____X,
  XX_X_XXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_0079[ 16] = { /* code 0079, LATIN SMALL LETTER Y */
  X_X__X__,
  ____XXX_,
  _X_XX___,
  ____XX__,
  _X_X_X_X,
  ___XX__X,
  _X___X_X,
  ____X___,
  XXXX_X__,
  XX__X___,
  XX__XXX_,
  X_X___XX,
  __XXX_X_,
  ___X_XX_,
  X__X_XX_,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_007A[ 16] = { /* code 007A, LATIN SMALL LETTER Z */
  X_XXX_XX,
  XX_X_XX_,
  _XX_XX_X,
  _XX_XXXX,
  X___X___,
  XXXX__XX,
  __XXX_X_,
  X______X,
  X_X__XXX,
  X___X__X,
  ____X___,
  _X__X_X_,
  X_X__X_X,
  X_X_XX_X,
  XXXX__X_,
  XXX_XXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_007B[ 16] = { /* code 007B, LEFT CURLY BRACKET */
  ____XX__,
  XX_XXXXX,
  _X_X__XX,
  XXXX__XX,
  X__X_XXX,
  _XXXXX__,
  X_X_X_XX,
  X__X__X_,
  _____XXX,
  X____XX_,
  _XX____X,
  XXX__XXX,
  ______XX,
  X__XXX__,
  ___X____,
  X__XX_X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_007C[ 16] = { /* code 007C, VERTICAL LINE */
  _X__X_X_,
  _____XXX,
  __X__XXX,
  __XX_X__,
  _XX_X___,
  _____XX_,
  _X_X_XXX,
  _X_____X,
  __XX____,
  XX_X_XX_,
  X_X_XX_X,
  XXX_XXX_,
  X_XXXXXX,
  X_XX_XXX,
  _XXX____,
  X_X_XX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_007D[ 16] = { /* code 007D, RIGHT CURLY BRACKET */
  _XXXXX__,
  _XXX_XX_,
  X__XX_XX,
  X_X_X___,
  _XXX__XX,
  ______X_,
  X___XXXX,
  _X_X_XXX,
  ____X___,
  X_X_X___,
  X__X_X__,
  _X___XXX,
  ___XXXXX,
  X_XXX_X_,
  X_X____X,
  X_X___XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_007E[ 16] = { /* code 007E, TILDE */
  _XX___X_,
  __X__X__,
  _XX__XXX,
  XX__X_XX,
  X___XXX_,
  _XXXXXX_,
  XX____XX,
  __XXXXX_,
  _XXX_XXX,
  XXXXX___,
  ___X_XX_,
  ____XXX_,
  XX____X_,
  __XX_X_X,
  X_X____X,
  X__X_X__};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_52D7[ 32] = { /* code 52D7 */
  XX_X_X_X,__X__XXX,
  XX__XX_X,XXXX__XX,
  XX_X____,XXXX__XX,
  XX____X_,_______X,
  XX_XXXX_,_XXX_XXX,
  __X_XX_X,_XXXX_XX,
  _____X__,__XX___X,
  __XXX_X_,XX__X__X,
  X__XX_X_,XXXX_X_X,
  XXX_XX_X,XX_X____,
  _____X__,____X_XX,
  X_X_X_XX,XXX_X_X_,
  X___X__X,X_XX_XX_,
  XXX___XX,____X_X_,
  XX_X___X,X_XXX__X,
  X__X_XXX,X_XXX_XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_5307[ 32] = { /* code 5307 */
  XX_XXXXX,X__X_X_X,
  XX___XXX,_X__XX__,
  ___X_X__,X_X_XXX_,
  __XXX_X_,XX___X__,
  XX__X__X,_X_XX_XX,
  ___XX_X_,XXXXXXXX,
  __XX___X,X_X____X,
  ____X___,XXXX____,
  X__XX_XX,_X___X_X,
  X____XX_,___X__XX,
  XXX__X__,XX_X_X__,
  XXX__XX_,_XX_XX_X,
  X___XXX_,X___X_X_,
  XX_XXXXX,X_X__XX_,
  XX__XX__,X_XXX_X_,
  ___X_X__,XX_XX_XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_5308[ 32] = { /* code 5308 */
  __X_XXXX,_X_X____,
  X____XXX,____XXXX,
  XXXX_XX_,XX_XXXXX,
  _XXX_XX_,_XXXX_X_,
  _____XX_,__XX_X_X,
  XXX_XXX_,X__XXXXX,
  __X_XXX_,X_X_XXXX,
  X___XXXX,XX_X__X_,
  __X___XX,X____X__,
  XX_X__X_,_XX_XX__,
  ______X_,X_X__X_X,
  X__XX___,X_XXX__X,
  _X_XX___,XX___X_X,
  __X_X___,X____XX_,
  XXX__X_X,__XX_X__,
  X_X__XXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_5327[ 32] = { /* code 5327 */
  X____XX_,XXX____X,
  _X__XX_X,XX_X_X__,
  ___X____,__XX___X,
  ___XX_XX,X_XXXXXX,
  _XXX____,__X_X_XX,
  _X_____X,__XXX_XX,
  __X__XXX,__X_XX_X,
  _X_XXX__,XXX_XXXX,
  _X__X_X_,___X_XXX,
  XX_XX___,__XX_XXX,
  XX______,XX__X__X,
  _XXX_X__,_XXX_XX_,
  _X_X_X_X,_XX___XX,
  X___XX_X,__X___X_,
  XXXXX_X_,X_X__XX_,
  __XX___X,_XX_X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontchinese_charcter_5357[ 32] = { /* code 5357 */
  X_XX_XX_,__XX____,
  _X___XXX,X_X_X_XX,
  XX_XX___,_X___X__,
  _X____XX,_XX_XX_X,
  XXXX_X_X,_X__XX__,
  X_XX____,X_XX_XX_,
  _X_XX_X_,X_X_____,
  _XX_XXX_,X_X__X_X,
  XXXXX___,XXX__XX_,
  X__XX___,XXX_XX__,
  __X__X_X,__XXX___,
  __XXXX_X,X____XX_,
  ______X_,__XXXX_X,
  __XX_XX_,_XX__XX_,
  XXX___XX,X_X_XXX_,
  ______X_,_X_X__XX};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontchinese_charcter_CharInfo[100] = {
   {   8,   8,  1, acGUI_Fontchinese_charcter_0020 } /* code 0020 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0021 } /* code 0021 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0022 } /* code 0022 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0023 } /* code 0023 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0024 } /* code 0024 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0025 } /* code 0025 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0026 } /* code 0026 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0027 } /* code 0027 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0028 } /* code 0028 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0029 } /* code 0029 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_002A } /* code 002A */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_002B } /* code 002B */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_002C } /* code 002C */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_002D } /* code 002D */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_002E } /* code 002E */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_002F } /* code 002F */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0030 } /* code 0030 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0031 } /* code 0031 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0032 } /* code 0032 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0033 } /* code 0033 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0034 } /* code 0034 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0035 } /* code 0035 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0036 } /* code 0036 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0037 } /* code 0037 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0038 } /* code 0038 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0039 } /* code 0039 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_003A } /* code 003A */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_003B } /* code 003B */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_003C } /* code 003C */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_003D } /* code 003D */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_003E } /* code 003E */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_003F } /* code 003F */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0040 } /* code 0040 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0041 } /* code 0041 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0042 } /* code 0042 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0043 } /* code 0043 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0044 } /* code 0044 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0045 } /* code 0045 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0046 } /* code 0046 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0047 } /* code 0047 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0048 } /* code 0048 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0049 } /* code 0049 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_004A } /* code 004A */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_004B } /* code 004B */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_004C } /* code 004C */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_004D } /* code 004D */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_004E } /* code 004E */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_004F } /* code 004F */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0050 } /* code 0050 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0051 } /* code 0051 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0052 } /* code 0052 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0053 } /* code 0053 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0054 } /* code 0054 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0055 } /* code 0055 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0056 } /* code 0056 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0057 } /* code 0057 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0058 } /* code 0058 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0059 } /* code 0059 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_005A } /* code 005A */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_005B } /* code 005B */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_005C } /* code 005C */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_005D } /* code 005D */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_005E } /* code 005E */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_005F } /* code 005F */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0060 } /* code 0060 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0061 } /* code 0061 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0062 } /* code 0062 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0063 } /* code 0063 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0064 } /* code 0064 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0065 } /* code 0065 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0066 } /* code 0066 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0067 } /* code 0067 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0068 } /* code 0068 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0069 } /* code 0069 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_006A } /* code 006A */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_006B } /* code 006B */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_006C } /* code 006C */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_006D } /* code 006D */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_006E } /* code 006E */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_006F } /* code 006F */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0070 } /* code 0070 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0071 } /* code 0071 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0072 } /* code 0072 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0073 } /* code 0073 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0074 } /* code 0074 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0075 } /* code 0075 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0076 } /* code 0076 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0077 } /* code 0077 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0078 } /* code 0078 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_0079 } /* code 0079 */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_007A } /* code 007A */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_007B } /* code 007B */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_007C } /* code 007C */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_007D } /* code 007D */
  ,{   8,   8,  1, acGUI_Fontchinese_charcter_007E } /* code 007E */
  ,{  16,  16,  1, acGUI_Fontchinese_charcter_52D7 } /* code 52D7 */
  ,{  16,  16,  1, acGUI_Fontchinese_charcter_5307 } /* code 5307 */
  ,{  16,  16,  1, acGUI_Fontchinese_charcter_5308 } /* code 5308 */
  ,{  16,  16,  1, acGUI_Fontchinese_charcter_5327 } /* code 5327 */
  ,{  16,  16,  1, acGUI_Fontchinese_charcter_5357 } /* code 5357 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontchinese_charcter_Prop5 = {
   0x5357 /* first character */
  ,0x5357 /* last character  */
  ,&GUI_Fontchinese_charcter_CharInfo[ 99] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontchinese_charcter_Prop4 = {
   0x5327 /* first character */
  ,0x5327 /* last character  */
  ,&GUI_Fontchinese_charcter_CharInfo[ 98] /* address of first character */
  ,&GUI_Fontchinese_charcter_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontchinese_charcter_Prop3 = {
   0x5307 /* first character */
  ,0x5308 /* last character  */
  ,&GUI_Fontchinese_charcter_CharInfo[ 96] /* address of first character */
  ,&GUI_Fontchinese_charcter_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontchinese_charcter_Prop2 = {
   0x52D7 /* first character */
  ,0x52D7 /* last character  */
  ,&GUI_Fontchinese_charcter_CharInfo[ 95] /* address of first character */
  ,&GUI_Fontchinese_charcter_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontchinese_charcter_Prop1 = {
   0x0020 /* first character */
  ,0x007E /* last character  */
  ,&GUI_Fontchinese_charcter_CharInfo[  0] /* address of first character */
  ,&GUI_Fontchinese_charcter_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontchinese_charcter = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontchinese_charcter_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

#endif