/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug 18 2014, 17:12:05                              *
*        (c) 2014 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END
#include <stdlib.h>
#include <string.h>

#include "DIALOG.h"
#include "FramewinDLG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0  (GUI_ID_USER + 0x00)
#define ID_TEXT_0  (GUI_ID_USER + 0x01)


// USER START (Optionally insert additional defines)
#define ID_TEXT_1   GUI_ID_USER + 0x02)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern GUI_CONST_STORAGE GUI_FONT GUI_FontDI24;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 400, 60, 800, 80, 0, 0x64, 0 },
  //{ TEXT_CreateIndirect, "ID_TEXT_0", ID_TEXT_1, 564, 130, 180, 58, 0, 0x64, 0 },
	//{ TEXT_CreateIndirect, "ID_TEXT_1", ID_TEXT_1, 600, 60, 180, 58, 0, 0x64, 0 },
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Text'
    //
	 GUI_UC_SetEncodeUTF8();
   //TEXT_SetDefaultFont(&GUI_Fontchangliang);//14x14 ∫∫◊÷ø‚£¨”√FontCvt V5.16◊™ªª
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextColor(hItem, 0x008000FF);
    
    TEXT_SetFont(hItem,&GUI_FontDI24);
		//TEXT_SetText(hItem,"English");
		TEXT_SetText(hItem,"\xe5\x8d\x97\xe4\xba\xac\xe5\xa4\xa7\xe5\xad\xa6");
	
		// hItem=TEXT_CreateEx( 400, 60, 253, 88,0,WM_CF_SHOW,TEXT_CF_HCENTER|TEXT_CF_VCENTER,ID_TEXT_1, "testyankui");//¡¡∂»    
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/

WM_HWIN CreateFramewin(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
